// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEZIUZRR1rFAGjsIVOUDhzF6Fua4XWzfw',
    appId: '1:60396017051:web:d97079e5b7f9b1abc7bd3e',
    messagingSenderId: '60396017051',
    projectId: 'student-51d79',
    authDomain: 'student-51d79.firebaseapp.com',
    storageBucket: 'student-51d79.firebasestorage.app',
    measurementId: 'G-YHKS3V5FTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVbTiBrQLOZHhYsYOfvfXZrLcgzcudtBg',
    appId: '1:60396017051:android:25990e49397d7a46c7bd3e',
    messagingSenderId: '60396017051',
    projectId: 'student-51d79',
    storageBucket: 'student-51d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHC6L49sSRCS1NBVZODBK68ifTAB1_yS8',
    appId: '1:60396017051:ios:66a73058315336e4c7bd3e',
    messagingSenderId: '60396017051',
    projectId: 'student-51d79',
    storageBucket: 'student-51d79.firebasestorage.app',
    androidClientId: '60396017051-fmcd4jemom9tckcbfq97b0l1c40ulcfg.apps.googleusercontent.com',
    iosClientId: '60396017051-op47ft87t3benr2m7enscr1uuphsdoe5.apps.googleusercontent.com',
    iosBundleId: 'com.ashtar.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHC6L49sSRCS1NBVZODBK68ifTAB1_yS8',
    appId: '1:60396017051:ios:66a73058315336e4c7bd3e',
    messagingSenderId: '60396017051',
    projectId: 'student-51d79',
    storageBucket: 'student-51d79.firebasestorage.app',
    androidClientId: '60396017051-fmcd4jemom9tckcbfq97b0l1c40ulcfg.apps.googleusercontent.com',
    iosClientId: '60396017051-op47ft87t3benr2m7enscr1uuphsdoe5.apps.googleusercontent.com',
    iosBundleId: 'com.ashtar.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEZIUZRR1rFAGjsIVOUDhzF6Fua4XWzfw',
    appId: '1:60396017051:web:dd406d63425f37e5c7bd3e',
    messagingSenderId: '60396017051',
    projectId: 'student-51d79',
    authDomain: 'student-51d79.firebaseapp.com',
    storageBucket: 'student-51d79.firebasestorage.app',
    measurementId: 'G-74MWZQD0MM',
  );
}
